### ISSUE TITLE
The images aren't centered with the text.

### ISSUE THREAD

**Issue by SampleProvider** [Swangie-Errangie/Detecting-Adblocker-without-JavaScript#1]
Screenshot:
![image](https://user-images.githubusercontent.com/68207888/107851333-2de04200-6dd7-11eb-9052-8aa3647c52d6.png)

**Comment by Suvanth-Erranki** [comment]
The demo works fine, just the images aren't aligned. This isn't an issue on my part as you can see below. I will try to fix though.
![image](https://user-images.githubusercontent.com/76885647/107859099-4cf5c880-6e05-11eb-85a6-7e6d0da969fb.png)

**Comment by SampleProvider** [comment]
Ok, cool. I will also try to fix it without javascript. If I fix it I can make a pull request.

**Comment by Swangie-Errangie** [comment]
I think this is possible with the @media query which could be used to measure the screen size and then change the images to center them.

**Comment by Suvanth-Erranki** [comment]
Fixed, please tell me if otherwise.

**Comment by SampleProvider** [comment]
Yes, I can confirm that this issue is fixed.
